### ISSUE TITLE
Login without Google Play Services

### ISSUE THREAD

**Issue by xmha97** [joaomanaia/newquiz#30]
Hi, can I login without Google Play Services?

![Screenshot_2023-03-14-01-11-50-094_com infinitepower newquiz](https://user-images.githubusercontent.com/23485114/224839475-23576588-835b-439f-bbd1-d8abbac55e87.jpg)

![Screenshot_2023-03-14-01-11-57-261_com infinitepower newquiz](https://user-images.githubusercontent.com/23485114/224839481-e56a97c7-bad8-47be-9cb8-38e04da5040c.jpg)

**Comment by joaomanaia** [comment]
Sorry for the late reply but I've been busy and haven't been able to fix the problem yet. Currently firebase auth does not need google play services, but the login with google does, that's why you are not able to login. That might be the problem. Or can be the firebase ui that is not updated to the recent firebase auth.

I'll try to see if for devices that don't have google play services I remove the login with google.

**Comment by joaomanaia** [comment]
I added a google play services availability checker, so when there is no google play services there will be only email login.

I'm having problems with emulators in my computer, so I cant create a emulator without google play services, can you test if now works. Download the debug apk from the [build action artifacts](https://github.com/joaomanaia/newquiz/actions/runs/4583301727).

**Comment by xmha97** [comment]
> I added a google play services availability checker, so when there is no google play services there will be only email login.
> 
> I'm having problems with emulators in my computer, so I cant create a emulator without google play services, can you test if now works. Download the debug apk from the [build action artifacts](https://github.com/joaomanaia/newquiz/actions/runs/4583301727).

I installed this version.
It's not working:(

![Screenshot_2023-04-02-11-29-13-487_com.infinitepower.newquiz.jpg](https://user-images.githubusercontent.com/23485114/229340227-b08cd118-2dd0-4193-83dd-a3270f5a6e78.jpg)

**Comment by joaomanaia** [comment]
Hi, I added the login without firebase auth ui. I think now you can login. Test with this debug [apk](https://github.com/joaomanaia/newquiz/actions/runs/4597381026)
