### ISSUE TITLE
Question displays until time runs out

### ISSUE THREAD

**Issue by zoroya1** [joaomanaia/newquiz#36]
In logoquiz when user select one answer, there is no confirm option and app can't recognize that user have given the answer, we have to wait until timer runs out for that qustion and only after that next question comes.

Maybe stops the timer for that question, when user has given the answer so that we won't have to wait for 25 sec. for next question

**Comment by zoroya1** [comment]
https://user-images.githubusercontent.com/128675129/228338670-91ed0e6e-080c-4230-9080-caaa6894df68.mp4

As you can see, ideally it should recognize that user has given answer and show new question, but here we have to wait for whole 25 seconds for new question to show up, maybe add a tickmark button to verify submit answer ?

Also, Mac'd option is not visible in first question

Izzyondroid repo inclusion will be great :)

**Comment by zoroya1** [comment]
Thank you for consodertation :)

**Comment by joaomanaia** [comment]
I changed the verify button and made the content to be scrollable, so now you can see the other answers.

https://user-images.githubusercontent.com/53819675/229289453-d2ddda5c-aad9-4854-a47b-390abd0a9cbf.mp4
