### ISSUE TITLE
Level System 

### ISSUE THREAD

**Issue by iamhero25** [joaomanaia/newquiz#61]
Hi,

Firstly, I am very impressed by your quiz app. Keep up the good work!

I tried the new level system and realized that there might be an issue with the level progress. In the attached screenshots user is at 390 xp at level 1 and needs 10 more xp for level two. However, when user reaches 400 xp the level progress for level is almost half way when it should be zero. 

![level_issue_image_one](https://github.com/joaomanaia/newquiz/assets/84644246/9560b8ac-028c-4405-a0af-559c6034cbed)

![level_issue_image_two](https://github.com/joaomanaia/newquiz/assets/84644246/399170fb-dc3e-4251-bfa8-6da1a76764ac)

**Comment by joaomanaia** [comment]
Hi,

Thank you for sharing your opinion about the game. :)

I made a commit to solve the problem, the code was calculating the current total xp with the next level total xp, which is wrong. So now it is calculated with the xp for the level the user is at. Now the progress bar behaves correctly.

**Comment by iamhero25** [comment]
Working now thanks!
