### ISSUE TITLE
Building the app

### ISSUE THREAD

**Issue by rayyanmm** [joaomanaia/newquiz#69]
I'm really new to open source apps from github and I struggled a lot with trying to build the app with firebase and android studio. I know that's a me problem so I just want to ask if someone has an APK or what guides I should read to gain more knowledge on how to get this to run on my phone?

**Comment by joaomanaia** [comment]
Hi! You can download the APK from the [Releases page](https://github.com/joaomanaia/newquiz/releases/), or if you need the latest build, you can find the APK in the GitHub Actions [artifacts](https://github.com/joaomanaia/newquiz/actions).

To build the APK with Firebase you need to:

1. Create a new Firebase project.
2. Register an app to the firebase project with the same package name of the app (com.infinitepower.newquiz).
3. Download and copy the google-services.json to the /app folder.
4. Select the normalDebug at build variants like this:

![image](https://github.com/user-attachments/assets/a897112c-82e2-49f5-b61a-2d274216251f)

Then you should be able to build the APK with firebase.

**Comment by rayyanmm** [comment]
Thank you so much! All good now
